---
# file: roles/os-centos/tasks/locale.yml
#
# os-centos Role
# Task for handling locale stuff
#
- name: set /etc/localtime
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    force: yes
  tags: locale
