---
- name: Check if RFX LSM is installed
  stat:
    path: /usr/local/sbin/lsm
  register: rfx_lsm_check
  changed_when: false
  always_run: yes
  tags: always

- name: Create rfx_lsm_installed variable.
  set_fact:
    rfx_lsm_installed: "{{ rfx_lsm_check.stat.exists|bool }}"
  always_run: yes
  tags: always

- name: Include the RFX LSM Installer Task
  include: install.yml
  when: rfx_lsm_installed != true and (install_rfx_lsm is defined and install_rfx_lsm == true)
