---
- name: Check if CloudFlare cPanel plugin is installed
  stat:
    path: /usr/local/cpanel/etc/cloudflare.json
  register: cloudflare_check
  changed_when: false
  always_run: yes
  tags: always

- name: Create cloudflare_installed variable.
  set_fact:
    cloudflare_installed: "{{ cloudflare_check.stat.exists|bool }}"
  always_run: yes
  tags: always

- name: Include the CloudFlare Installer Task
  include: install.yml
  when: cloudflare_installed != true and (install_cloudflare is defined and install_cloudflare == true)
