---
- name: Check if PostgreSQL is installed
  stat:
    path: /usr/bin/psql
  register: pgsql_check
  changed_when: false
  always_run: yes
  tags: always

- name: Create pgsql_installed variable.
  set_fact:
    pgsql_installed: "{{ pgsql_check.stat.exists|bool }}"
  always_run: yes
  tags: always

- name: Include the PostgreSQL Installer Task
  include: install.yml
  when: pgsql_installed != true and (install_pgsql is defined and install_pgsql == true)
