---
- name: Check if RFX SIM is installed
  stat:
    path: /usr/local/sbin/sim
  register: rfx_sim_check
  changed_when: false
  always_run: yes
  tags: always

- name: Create rfx_sim_installed variable.
  set_fact:
    rfx_sim_installed: "{{ rfx_sim_check.stat.exists|bool }}"
  always_run: yes
  tags: always

- name: Include the RFX SIM Installer Task
  include: install.yml
  when: rfx_sim_installed != true and (install_rfx_sim is defined and install_rfx_sim == true)
