---
- name: Check if RFX PRM is installed
  stat:
    path: /usr/local/sbin/prm
  register: rfx_prm_check
  changed_when: false
  always_run: yes
  tags: always

- name: Create rfx_prm_installed variable.
  set_fact:
    rfx_prm_installed: "{{ rfx_prm_check.stat.exists|bool }}"
  always_run: yes
  tags: always

- name: Include the RFX PRM Installer Task
  include: install.yml
  when: rfx_prm_installed != true and (install_rfx_prm is defined and install_rfx_prm == true)
